import * as z from 'zod'

/**
 * Money, on the wire.
 *
 * Internally every amount is an integer count of nano-USD (1 = 1e-9 USD) held in
 * a `bigint`. JSON has no bigint, so the wire format is the same integer written
 * in base 10 as a string.
 *
 * Never a float. `0.1 + 0.2` cannot exist in code that moves money, and an image
 * priced at US$ 0.0005 is real — rounding to cents would collapse two routes with
 * different prices into the same number, which is the product we are building.
 *
 * A signed value is allowed because ledger entries carry direction: a reservation
 * is positive, a refund is negative.
 */
export const nanoUsd = z
  .string()
  .regex(/^-?(0|[1-9]\d{0,18})$/, 'nano-USD must be a base-10 integer, not a decimal')
  .describe('Integer count of nano-USD (1 = 1e-9 USD), base 10, as a string')

export type NanoUsd = z.infer<typeof nanoUsd>

/**
 * Idempotency key, generated by the CLIENT and carried by every mutation.
 *
 * If the server generated it, a retry from the client would create a new command
 * and duplicate the effect. Here that means generating the image twice and being
 * charged twice, so this is not a backend detail — it is a contract field.
 */
export const commandId = z.uuid().describe('Client-generated idempotency key (UUID)')

export const userId = z.uuid()
export const email = z.email().max(320).toLowerCase()

/**
 * 12 characters is the floor, not a recommendation. The upper bound exists so a
 * megabyte-long password cannot turn scrypt into a denial of service.
 */
export const passwordSchema = z.string().min(12).max(200)

export const timestamp = z.iso.datetime({ offset: true })

export const userRole = z.enum(['owner', 'user'])
export type UserRole = z.infer<typeof userRole>

/**
 * "day" and not "session": a session cap sounds like it follows a browser tab,
 * and a worker that keeps generating after the tab closes would make that name a
 * lie. "Since midnight where you live" is something both the code and the user
 * can point at.
 */
export const budgetWindow = z.enum(['month', 'day'])
export type BudgetWindow = z.infer<typeof budgetWindow>

export const publicUser = z.object({
  id: userId,
  email,
  name: z.string().max(120).nullable(),
  role: userRole,
  /** IANA zone. It is what decides where the month of a spending cap begins. */
  timezone: z.string().max(64),
  createdAt: timestamp,
})

export type PublicUser = z.infer<typeof publicUser>

export const budget = z.object({
  window: budgetWindow,
  windowStart: timestamp,
  windowEnd: timestamp,
  capNanoUsd: nanoUsd,
  reservedNanoUsd: nanoUsd,
  spentNanoUsd: nanoUsd,
  /** Set when settlement exceeded the cap. The money was already spent at the provider. */
  exceededAt: timestamp.nullable(),
  alertPercent: z.number().int().min(1).max(100),
})

export type Budget = z.infer<typeof budget>
