import * as z from 'zod'

/**
 * Money, on the wire.
 *
 * Internally every amount is an integer count of nano-USD (1 = 1e-9 USD) held in
 * a `bigint`. JSON has no bigint, so the wire format is the same integer written
 * in base 10 as a string.
 *
 * Never a float. `0.1 + 0.2` cannot exist in code that moves money, and an image
 * priced at US$ 0.0005 is real — rounding to cents would collapse two routes with
 * different prices into the same number, which is the product we are building.
 *
 * A signed value is allowed because ledger entries carry direction: a reservation
 * is positive, a refund is negative.
 */
export const nanoUsd = z
  .string()
  .regex(/^-?(0|[1-9]\d{0,18})$/, 'nano-USD must be a base-10 integer, not a decimal')
  .describe('Integer count of nano-USD (1 = 1e-9 USD), base 10, as a string')

export type NanoUsd = z.infer<typeof nanoUsd>

/**
 * Idempotency key, generated by the CLIENT and carried by every mutation.
 *
 * If the server generated it, a retry from the client would create a new command
 * and duplicate the effect. Here that means generating the image twice and being
 * charged twice, so this is not a backend detail — it is a contract field.
 */
export const commandId = z.uuid().describe('Client-generated idempotency key (UUID)')

export const userId = z.uuid()
export const email = z.email().max(320).toLowerCase()

/**
 * 12 characters is the floor, not a recommendation. The upper bound exists so a
 * megabyte-long password cannot turn scrypt into a denial of service.
 */
export const passwordSchema = z.string().min(12).max(200)

export const timestamp = z.iso.datetime({ offset: true })

export const userRole = z.enum(['owner', 'user'])
export type UserRole = z.infer<typeof userRole>

/**
 * "day" and not "session": a session cap sounds like it follows a browser tab,
 * and a worker that keeps generating after the tab closes would make that name a
 * lie. "Since midnight where you live" is something both the code and the user
 * can point at.
 */
export const budgetPeriod = z.enum(['month', 'day'])
export type BudgetWindow = z.infer<typeof budgetPeriod>

export const publicUser = z.object({
  id: userId,
  email,
  name: z.string().max(120).nullable(),
  role: userRole,
  /** IANA zone. It is what decides where the month of a spending cap begins. */
  timezone: z.string().max(64),
  createdAt: timestamp,
})

export type PublicUser = z.infer<typeof publicUser>

export const budget = z.object({
  period: budgetPeriod,
  periodStart: timestamp,
  periodEnd: timestamp,
  capNanoUsd: nanoUsd,
  reservedNanoUsd: nanoUsd,
  spentNanoUsd: nanoUsd,
  /** Set when settlement exceeded the cap. The money was already spent at the provider. */
  exceededAt: timestamp.nullable(),
  alertPercent: z.number().int().min(1).max(100),
})

export type Budget = z.infer<typeof budget>

// --- M2: providers and the key vault -------------------------------------------

export const providerSlug = z.string().min(1).max(40)

export const providerInfo = z.object({
  slug: providerSlug,
  name: z.string(),
  active: z.boolean(),
  mode: z.enum(['sync', 'queue', 'both']),
  /** Whether the provider reports what a generation actually cost. */
  costInResponse: z.enum(['exact', 'units', 'none']),
  /** How long the provider's output URL lives. BFL is 600 seconds. */
  outputTtlSeconds: z.number().int().nullable(),
  docUrl: z.url().nullable(),
  /** Compliance facts the user must see BEFORE spending. */
  notice: z.string().nullable(),
})

export type ProviderInfo = z.infer<typeof providerInfo>

/**
 * What a screen may know about a stored key.
 *
 * There is no secret in this shape and no route returns one — not even masked
 * behind a "reveal" button. A read path is what an authorization bug turns into a
 * mass leak, and an XSS would drain the vault through the user's own session.
 */
export const credential = z.object({
  id: z.uuid(),
  provider: providerSlug,
  kind: z.enum(['api_key', 'oauth_refresh', 'webhook_secret']),
  label: z.string().max(80).nullable(),
  lastFour: z.string().length(4),
  status: z.enum(['active', 'invalid', 'revoked']),
  verifiedAt: timestamp.nullable(),
  lastUsedAt: timestamp.nullable(),
  createdAt: timestamp,
})

export type Credential = z.infer<typeof credential>

/**
 * `no_probe` is not a failure. Six of the thirteen providers expose no free,
 * documented endpoint that authenticates, so the key is stored and the screen
 * says it could not be checked — rather than showing a tick that means nothing.
 */
export const verification = z.object({
  status: z.enum([
    'valid',
    'invalid',
    'no_credit',
    'unverified_account',
    'rate_limited',
    'unavailable',
    'no_probe',
  ]),
  retryAfterSeconds: z.number().int().nonnegative().optional(),
})

export type Verification = z.infer<typeof verification>

/**
 * The secret itself, on its way IN and never on its way out.
 *
 * Bounded so a megabyte pasted into the box cannot become a megabyte of
 * ciphertext in a row, and trimmed because a trailing newline from a copy-paste
 * is the most common reason a perfectly good key is rejected.
 */
export const providerSecret = z.string().trim().min(8).max(4096)

/**
 * One row of the price index.
 *
 * `costNanoUsd` is null when the price cannot honestly be compared — a
 * per-second video rate, or a per-token price with no tokens-per-image figure
 * recorded. `explanation` always says which, because a blank cell in a price
 * table is read as "free" or as a bug.
 */
export const indexEntry = z.object({
  modelId: z.string(),
  /**
   * Identidade do modelo atravessando provedores.
   *
   * `FLUX.1 [schnell]` no fal e `black-forest-labs/FLUX-1-schnell` na DeepInfra
   * sao os mesmos pesos, e sem esta chave a tela nao consegue mostrar a unica
   * coisa que o produto existe para mostrar: o mesmo modelo custando precos
   * diferentes. `matchedBy: 'unresolved'` e resposta legitima — o modelo fica com
   * a linha dele, que nunca esta errado.
   */
  modelKey: z.string(),
  modelLabel: z.string(),
  maker: z.string().nullable(),
  matchedBy: z.enum(['known-family', 'unresolved']),
  provider: providerSlug,
  providerName: z.string(),
  name: z.string(),
  family: z.string().nullable(),
  tasks: z.array(z.string()),
  watermark: z.enum(['synthid', 'none', 'unknown']),
  costNanoUsd: nanoUsd.nullable(),
  explanation: z.string(),
  basis: z.string().nullable(),
  source: z.string().nullable(),
  collectedAt: timestamp.nullable(),
  method: z.string().nullable(),
  /** Above thirty days old a price leaves the ranking instead of aging into a lie. */
  fresh: z.boolean(),
  note: z.string().nullable(),
})

export type IndexEntry = z.infer<typeof indexEntry>
